export const FETCH_LIST_CHAT = 'FETCH_LIST_CHAT';
export const APPEND_CHAT = 'APPEND_CHAT';
export const FETCH_MEMBER_CHAT = 'FETCH_MEMBER_CHAT';

export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';

export const LOAD_CHAT = 'LOAD_CHAT';
export const LOAD_CHAT_SUCCESS = 'LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_FAIL = 'LOAD_CHAT_FAIL';

export const CHAT_IMAGE = 'CHAT_IMAGE';
export const CHAT_IMAGE_SUCCESS = 'CHAT_IMAGE_SUCCESS';
export const CHAT_IMAGE_FAIL = 'CHAT_IMAGE_FAIL';

export const CHAT_FILE = 'CHAT_FILE';
export const CHAT_FILE_SUCCESS = 'CHAT_FILE_SUCCESS';
export const CHAT_FILE_FAIL = 'CHAT_FILE_FAIL';

export const CHAT_FORWARD_FILE = 'CHAT_FORWARD_FILE';
export const CHAT_FORWARD_FILE_SUCCESS = 'CHAT_FORWARD_FILE_SUCCESS';
export const CHAT_FORWARD_FILE_FAIL = 'CHAT_FORWARD_FILE_FAIL';

export const CHAT_STICKER = 'CHAT_STICKER';
export const CHAT_STICKER_SUCCESS = 'CHAT_STICKER_SUCCESS';
export const CHAT_STICKER_FAIL = 'CHAT_STICKER_FAIL';

export const GET_CHAT_NOT_VIEWED = 'GET_CHAT_NOT_VIEWED';
export const GET_CHAT_NOT_VIEWED_SUCCESS = 'GET_CHAT_NOT_VIEWED_SUCCESS';
export const GET_CHAT_NOT_VIEWED_FAIL = 'GET_CHAT_NOT_VIEWED_FAIL';

export const GET_NOTI_CHAT = 'GET_NOTI_CHAT';
export const GET_NOTI_CHAT_SUCCESS = 'GET_NOTI_CHAT_SUCCESS';
export const GET_NOTI_CHAT_FAIL = 'GET_NOTI_CHAT_FAIL';

export const FORWARD_CHAT = 'FORWARD_CHAT';
export const FORWARD_CHAT_SUCCESS = 'FORWARD_CHAT_SUCCESS';
export const FORWARD_CHAT_FAIL = 'FORWARD_CHAT_FAIL';

export const GET_LIST_STICKERS = 'GET_LIST_STICKERS';
export const GET_LIST_STICKERS_SUCCESS = 'GET_LIST_STICKERS_SUCCESS';
export const GET_LIST_STICKERS_FAIL = 'GET_LIST_STICKERS_FAIL';

export const LOAD_LIST_TASK = 'LOAD_LIST_TASK';
export const LOAD_LIST_TASK_SUCCESS = 'LOAD_LIST_TASK_SUCCESS';
export const LOAD_LIST_TASK_FAIL = 'LOAD_LIST_TASK_FAIL';

export const SEARCH_CHAT = 'SEARCH_CHAT';
export const ON_UPLOADING = 'ON_UPLOADING';
export const TAG_MEMBER = 'TAG_MEMBER';
export const CLEAR_TAGS = 'CLEAR_TAGS';
export const CHANGE_STICKER_KEYWORD = 'CHANGE_STICKER_KEYWORD';

export const GET_EMOTIONS = 'GET_EMOTIONS';
export const GET_EMOTIONS_SUCCESS = 'GET_EMOTIONS_SUCCESS';
export const GET_EMOTIONS_FAIL = 'GET_EMOTIONS_FAIL';

export const CHAT_EMOTION = 'CHAT_EMOTION';
export const CHAT_EMOTION_SUCCESS = 'CHAT_EMOTION_SUCCESS';
export const CHAT_EMOTION_FAIL = 'CHAT_EMOTION_FAIL';

export const GET_EMOTIONS_REACT_MEMBER = 'GET_EMOTIONS_REACT_MEMBER';
export const GET_EMOTIONS_REACT_MEMBER_SUCCESS = 'GET_EMOTIONS_REACT_MEMBER_SUCCESS';
export const GET_EMOTIONS_REACT_MEMBER_FAIL = 'GET_EMOTIONS_REACT_MEMBER_FAIL';

export const CREATE_CHAT_TEXT = 'CREATE_CHAT_TEXT';
export const CREATE_CHAT_TEXT_SUCCESS = 'CREATE_CHAT_TEXT_SUCCESS';
export const CREATE_CHAT_TEXT_FAIL = 'CREATE_CHAT_TEXT_FAIL';

export const GET_VIEWED_CHAT = 'GET_VIEWED_CHAT';
export const GET_VIEWED_CHAT_SUCCESS = 'GET_VIEWED_CHAT_SUCCESS';
export const GET_VIEWED_CHAT_FAIL = 'GET_VIEWED_CHAT_FAIL';
export const OPEN_DETAIL_REMIND = 'OPEN_DETAIL_REMIND';
export const OPEN_CREATE_REMIND = 'OPEN_CREATE_REMIND';

export const GET_REMIND_DETAIL = 'GET_REMIND_DETAIL';
export const GET_REMIND_DETAIL_SUCCESS = 'GET_REMIND_DETAIL_SUCCESS';
export const GET_REMIND_DETAIL_FAIL = 'GET_REMIND_DETAIL_FAIL';

export const GET_SUBTASK_DETAIL = 'GET_SUBTASK_DETAIL';
export const GET_SUBTASK_DETAIL_SUCCESS = 'GET_SUBTASK_DETAIL_SUCCESS';
export const GET_SUBTASK_DETAIL_FAIL = 'GET_SUBTASK_DETAIL_FAIL';
export const OPEN_DETAIL_SUB_TASK = 'OPEN_DETAIL_SUB_TASK';
export const OPEN_DETAIL_OFFER = 'OPEN_DETAIL_OFFER';
export const OPEN_DETAIL_DEMAND = 'OPEN_DETAIL_DEMAND';

export const GET_OFFER_DETAIL = 'GET_OFFER_DETAIL';
export const GET_OFFER_DETAIL_SUCCESS = 'GET_OFFER_DETAIL_SUCCESS';
export const GET_OFFER_DETAIL_FAIL = 'GET_OFFER_DETAIL_FAIL';

export const GET_DEMAND_DETAIL = 'GET_DEMAND_DETAIL';
export const GET_DEMAND_DETAIL_SUCCESS = 'GET_DEMAND_DETAIL_SUCCESS';
export const GET_DEMAND_DETAIL_FAIL = 'GET_DEMAND_DETAIL_FAIL';

export const CHAT_QUICK_LIKE = 'CHAT_QUICK_LIKE';
export const CHAT_QUICK_LIKE_SUCCESS = 'CHAT_QUICK_LIKE_SUCCESS';
export const CHAT_QUICK_LIKE_FAIL = 'CHAT_QUICK_LIKE_FAIL';
export const REMOVE_CHAT_BY_ID = 'REMOVE_CHAT_BY_ID';
export const JOIN_CHAT_EVENT = 'JOIN_CHAT_EVENT';
export const JOIN_PROJECT_EVENT = 'JOIN_PROJECT_EVENT';

export const CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER = 'CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER';
export const CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER_SUCCESS = 'CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER_SUCCESS';
export const CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER_FAIL = 'CREATE_CHAT_FILE_FROM_GOOGLE_DRIVER_FAIL';
export const OPEN_DETAIL_MEMBER = 'OPEN_DETAIL_MEMBER';

export const GET_GIRD_LIST_TASK = 'GET_GIRD_LIST_TASK';
export const GET_GIRD_LIST_TASK_SUCCESS = 'GET_GIRD_LIST_TASK_SUCCESS';
export const GET_GIRD_LIST_TASK_FAIL = 'GET_GIRD_LIST_TASK_FAIL';
export const UPDATE_CHAT_STATE = 'UPDATE_CHAT_STATE';
export const SHOW_IMAGES_LIST = 'SHOW_IMAGES_LIST';

export const GET_DATA_PIN_ON_TASK_CHAT = 'GET_DATA_PIN_ON_TASK_CHAT';
export const GET_DATA_PIN_ON_TASK_CHAT_SUCCESS = 'GET_DATA_PIN_ON_TASK_CHAT_SUCCESS';
export const GET_DATA_PIN_ON_TASK_CHAT_FAIL = 'GET_DATA_PIN_ON_TASK_CHAT_FAIL';
export const OPEN_SHARE_FILE_MODAL = 'OPEN_SHARE_FILE_MODAL';