export const FETCH_LIST_CHAT = 'FETCH_LIST_CHAT';
export const APPEND_CHAT = 'APPEND_CHAT';
export const FETCH_MEMBER_CHAT = 'FETCH_MEMBER_CHAT';

export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';