export const FETCH_LIST_CHAT = 'FETCH_LIST_CHAT';
export const APPEND_CHAT = 'APPEND_CHAT';
export const FETCH_MEMBER_CHAT = 'FETCH_MEMBER_CHAT';

export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';

export const LOAD_CHAT = 'LOAD_CHAT';
export const LOAD_CHAT_SUCCESS = 'LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_FAIL = 'LOAD_CHAT_FAIL';

export const CHAT_IMAGE = 'CHAT_IMAGE';
export const CHAT_IMAGE_SUCCESS = 'CHAT_IMAGE_SUCCESS';
export const CHAT_IMAGE_FAIL = 'CHAT_IMAGE_FAIL';

export const CHAT_FILE = 'CHAT_FILE';
export const CHAT_FILE_SUCCESS = 'CHAT_FILE_SUCCESS';
export const CHAT_FILE_FAIL = 'CHAT_FILE_FAIL';

export const CHAT_FORWARD_FILE = 'CHAT_FORWARD_FILE';
export const CHAT_FORWARD_FILE_SUCCESS = 'CHAT_FORWARD_FILE_SUCCESS';
export const CHAT_FORWARD_FILE_FAIL = 'CHAT_FORWARD_FILE_FAIL';

export const CHAT_STICKER = 'CHAT_STICKER';
export const CHAT_STICKER_SUCCESS = 'CHAT_STICKER_SUCCESS';
export const CHAT_STICKER_FAIL = 'CHAT_STICKER_FAIL';

export const GET_CHAT_NOT_VIEWED = 'GET_CHAT_NOT_VIEWED';
export const GET_CHAT_NOT_VIEWED_SUCCESS = 'GET_CHAT_NOT_VIEWED_SUCCESS';
export const GET_CHAT_NOT_VIEWED_FAIL = 'GET_CHAT_NOT_VIEWED_FAIL';

export const GET_NOTI_CHAT = 'GET_NOTI_CHAT';
export const GET_NOTI_CHAT_SUCCESS = 'GET_NOTI_CHAT_SUCCESS';
export const GET_NOTI_CHAT_FAIL = 'GET_NOTI_CHAT_FAIL';

export const FORWARD_CHAT = 'FORWARD_CHAT';
export const FORWARD_CHAT_SUCCESS = 'FORWARD_CHAT_SUCCESS';
export const FORWARD_CHAT_FAIL = 'FORWARD_CHAT_FAIL';

export const GET_LIST_STICKERS = 'GET_LIST_STICKERS';
export const GET_LIST_STICKERS_SUCCESS = 'GET_LIST_STICKERS_SUCCESS';
export const GET_LIST_STICKERS_FAIL = 'GET_LIST_STICKERS_FAIL';

export const LOAD_LIST_TASK = 'LOAD_LIST_TASK';
export const LOAD_LIST_TASK_SUCCESS = 'LOAD_LIST_TASK_SUCCESS';
export const LOAD_LIST_TASK_FAIL = 'LOAD_LIST_TASK_FAIL';

export const SEARCH_CHAT = 'SEARCH_CHAT';
export const ON_UPLOADING = 'ON_UPLOADING';
export const TAG_MEMBER = 'TAG_MEMBER';
export const CLEAR_TAGS = 'CLEAR_TAGS';

export const GET_EMOTIONS = 'GET_EMOTIONS';
export const GET_EMOTIONS_SUCCESS = 'GET_EMOTIONS_SUCCESS';
export const GET_EMOTIONS_FAIL = 'GET_EMOTIONS_FAIL';

export const CHAT_EMOTION = 'CHAT_EMOTION';
export const CHAT_EMOTION_SUCCESS = 'CHAT_EMOTION_SUCCESS';
export const CHAT_EMOTION_FAIL = 'CHAT_EMOTION_FAIL';

export const GET_EMOTIONS_REACT_MEMBER = 'GET_EMOTIONS_REACT_MEMBER';
export const GET_EMOTIONS_REACT_MEMBER_SUCCESS = 'GET_EMOTIONS_REACT_MEMBER_SUCCESS';
export const GET_EMOTIONS_REACT_MEMBER_FAIL = 'GET_EMOTIONS_REACT_MEMBER_FAIL';