export const CALENDAR_PAGE_PERMISSION = "ACTION_CALENDAR_PAGE_PERMISSION";
export const CALENDAR_PAGE_PERMISSION_SUCCESS = "ACTION_CALENDAR_PAGE_PERMISSION_SUCCESS";
export const CALENDAR_PAGE_PERMISSION_FAIL = "ACTION_CALENDAR_PAGE_PERMISSION_FAIL";