export const LIST_TASK_MEMBER = 'ACTION_LIST_TASK_MEMBER';
export const LIST_TASK_MEMBER_SUCCESS = 'ACTION_LIST_TASK_MEMBER_SUCCESS';
export const LIST_TASK_MEMBER_FAIL = 'ACTION_LIST_TASK_MEMBER_FAIL';