export const LIST_TASK = 'ACTION_LIST_TASK';
export const LIST_TASK_SUCCESS = 'ACTION_LIST_TASK_SUCCESS';
export const LIST_TASK_FAIL = 'ACTION_LIST_TASK_FAIL';
export const LIST_TASK_RESET = 'ACTION_LIST_TASK_RESET';
