export const LIST_TASK = "ACTION_LIST_TASK";
export const LIST_TASK_SUCCESS = "ACTION_LIST_TASK_SUCCESS";
export const LIST_TASK_FAIL = "ACTION_LIST_TASK_FAIL";
export const LIST_TASK_RESET = "ACTION_LIST_TASK_RESET";

export const ADD_GROUP_TASK = "ACTION_ADD_GROUP_TASK";
export const ADD_GROUP_TASK_SUCCESS = "ACTION_ADD_GROUP_TASK_SUCCESS";
export const ADD_GROUP_TASK_FAILED = "ACTION_ADD_GROUP_TASK_FAILED";

export const ADD_NEW_TASK_TEMP = "ADD_NEW_TASK_TEMP";
