export const CREATE_USER_ROLE = 'ACTION_CREATE_USER_ROLE';
export const CREATE_USER_ROLE_SUCCESS = 'ACTION_CREATE_USER_ROLE_SUCCESS';
export const CREATE_USER_ROLE_FAIL = 'ACTION_CREATE_USER_ROLE_FAIL';
