export const DELETE_USER_ROLE = 'ACTION_DELETE_USER_ROLE';
export const DELETE_USER_ROLE_SUCCESS = 'ACTION_DELETE_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_FAIL = 'ACTION_DELETE_USER_ROLE_FAIL';
