export const LIST_USER_ROLE = 'ACTION_LIST_USER_ROLE';
export const LIST_USER_ROLE_SUCCESS = 'ACTION_LIST_USER_ROLE_SUCCESS';
export const LIST_USER_ROLE_FAIL = 'ACTION_LIST_USER_ROLE_FAIL';
export const LIST_USER_ROLE_RESET = 'ACTION_LIST_USER_ROLE_RESET';
