export const UPDATE_USER_ROLE = 'ACTION_UPDATE_USER_ROLE';
export const UPDATE_USER_ROLE_SUCCESS = 'ACTION_UPDATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_FAIL = 'ACTION_UPDATE_USER_ROLE_FAIL';
