export const CREATE_GROUP_TASK = 'ACTION_CREATE_GROUP_TASK';
export const CREATE_GROUP_TASK_SUCCESS = 'ACTION_CREATE_GROUP_TASK_SUCCESS';
export const CREATE_GROUP_TASK_FAIL = 'ACTION_CREATE_GROUP_TASK_FAIL';