export const DEFAULT_GROUP_TASK = "ACTION_DEFAULT_GROUP_TASK";
export const DEFAULT_GROUP_TASK_SUCCESS = "ACTION_DEFAULT_GROUP_TASK_SUCCESS";
export const DEFAULT_GROUP_TASK_FAIL = "ACTION_DEFAULT_GROUP_TASK_FAIL";
