export const DELETE_GROUP_TASK = 'ACTION_DELETE_GROUP_TASK';
export const DELETE_GROUP_TASK_SUCCESS = 'ACTION_DELETE_GROUP_TASK_SUCCESS';
export const DELETE_GROUP_TASK_FAIL = 'ACTION_DELETE_GROUP_TASK_FAIL';