export const GET_ALL_GROUP_TASK = 'ACTION_GET_ALL_GROUP_TASK';
export const GET_ALL_GROUP_TASK_SUCCESS = 'ACTION_GET_ALL_GROUP_TASK_SUCCESS';
export const GET_ALL_GROUP_TASK_FAIL = 'ACTION_GET_ALL_GROUP_TASK_FAIL';