export const UPDATE_GROUP_TASK = 'ACTION_UPDATE_GROUP_TASK';
export const UPDATE_GROUP_TASK_SUCCESS = 'ACTION_UPDATE_GROUP_TASK_SUCCESS';
export const UPDATE_GROUP_TASK_FAIL = 'ACTION_UPDATE_GROUP_TASK_FAIL';