export const project = '/project'           // Du an
export const member = '/member'             // Thanh vien
export const report = '/report'             // Bao cao
export const document = '/document'         // Tai lieu
export const task = '/task'                 // Cong viec
export const jobDetail = '/job-detail'      // Chi tiet cong viec
export const information = '/information'   // Thong tin
export const user = '/user'                 // Nguoi dung
export const test = '/__test__'