export const DETAIL_STATUS = 'ACTION_DETAIL_STATUS';
export const DETAIL_STATUS_SUCCESS = 'ACTION_DETAIL_STATUS_SUCCESS';
export const DETAIL_STATUS_FAIL = 'ACTION_DETAIL_STATUS_FAIL';
export const DETAIL_STATUS_RESET = 'ACTION_DETAIL_STATUS_RESET';
