export const UPDATE_STATUS_COPY = 'ACTION_UPDATE_STATUS_COPY';
export const UPDATE_STATUS_COPY_SUCCESS = 'ACTION_UPDATE_STATUS_COPY_SUCCESS';
export const UPDATE_STATUS_COPY_FAIL = 'ACTION_UPDATE_STATUS_COPY_FAIL';
