export const UPDATE_PIN_BOARD_SETTING = 'ACTION_UPDATE_PIN_BOARD_SETTING';
export const UPDATE_PIN_BOARD_SETTING_SUCCESS = 'ACTION_UPDATE_PIN_BOARD_SETTING_SUCCESS';
export const UPDATE_PIN_BOARD_SETTING_FAIL = 'ACTION_UPDATE_PIN_BOARD_SETTING_FAIL';
