export const UPDATE_STATUS_VIEW = 'ACTION_UPDATE_STATUS_VIEW';
export const UPDATE_STATUS_VIEW_SUCCESS = 'ACTION_UPDATE_STATUS_VIEW_SUCCESS';
export const UPDATE_STATUS_VIEW_FAIL = 'ACTION_UPDATE_STATUS_VIEW_FAIL';
