export const UPDATE_STATUS_DATE = 'ACTION_UPDATE_STATUS_DATE';
export const UPDATE_STATUS_DATE_SUCCESS = 'ACTION_UPDATE_STATUS_DATE_SUCCESS';
export const UPDATE_STATUS_DATE_FAIL = 'ACTION_UPDATE_STATUS_DATE_FAIL';
