export const statistic = {
  offer_of_me_sending: "static.offer_of_me_sending",
  offer_of_me_approved: "static.offer_of_me_approved",
  offer_of_me_monitoring: "static.offer_of_me_monitoring",
  offer_status_waiting: "static.offer_status_waiting",
  offer_status_approved: "static.offer_status_approved",
  offer_status_cancel: "static.offer_status_cancel",
  offer_piority_normal: "static.offer_piority_normal",
  offer_piority_urgent: "static.offer_piority_urgent",
  offer_piority_very_urgent: "static.offer_piority_very_urgent",
};
export const roleAttrs = {

};
export const recent = {

};


export const taskAtrrs = {
  id: "id",
  project_id: "project_id",
  name: "name",
  user_create_avatar: "user_create.avatar",
  user_create_name: "user_create.name",
  created_at: "created_at",
  status_code: "status_code",
  status_name: "status_name",
  priority_code: "priority_code",
  priority_name: "priority_name",
  complete: "complete",
  number_member: "number_member",
  duration_unit: "duration_unit",
  duration_value: "duration_value",
  time_end: "time_end",
  haveNewChat: "haveNewChat",
  project: "project",
  description: "description",
  group_task: "group_task",
  group_task_name: "group_task_name",
  updated_complete_at: "updated_complete_at",
  is_ghim: "is_ghim",
  is_turn_of_notification: "is_turn_of_notification",
  complete_with_time: "complete_with_time",
  state_code: "state_code",
  state_name: "state_name",
  assign_code: "assign_code",
  assign_name: "assign_name",
  time_implement: "time_implement",
  start_time: "start_time",
  start_date: "start_date",
  end_time: "end_time",
  end_date: "end_date",
  total_subtask: "total_subtask",
  total_subtask_complete: "total_subtask_complete",
  total_remind: "total_remind",
  total_file: "total_file",
  total_img: "total_img",
  total_link: "total_link",
  total_location: "total_location",
  total_offer: "total_offer",
  total_offer_approved: "total_offer_approved",
  total_command: "total_command",
  members: "members",
  members_id: "members.id",
  members_name: "members.name",
  members_avatar: "members.avatar",
  members_roles: "members.roles",
  user_create: "user_create",
  user_create_id: "user_create.id",
  user_create_roles: "user_create.roles",
  date_create: "date_create",
  url_redirect: "url_redirect",
};

export const labels = {
  overview: "Tổng quan",
  pageTitle: "Đề xuất của bạn",
  pageTitleOfferByGroup: "Đề xuất theo nhóm",
  pageTitleOfferByProject: "Đề xuất theo dự án",
  pageTitleOfferByDepartment: "Đề xuất theo bộ phận",
  pageTitleOfferDetailOffer: "Chi tiết đề xuất",
  recently: "Gần đây",
  group: "Nhóm",
  project: "Dự án",
  department: "Bộ phận",
  detail_offer: "Chi tiết đề xuất",
  offer_by_group: "Đề xuất theo nhóm",
  offer_by_project: "Đề xuất theo dự án",
  offer_by_department: "Đề xuất theo bộ phận",
  offer_of_me_sending: "Gửi đi",
  offer_status_approved: "Phê duyệt",
  offer_of_me_approved: "Phê duyệt",
  offer_of_me_monitoring: "Giám sát",
  offer_status_waiting: "Chờ duyệt",
  offer_status_cancel: "Bị từ chối",
  offer_piority_normal: "Bình thường",
  offer_piority_urgent: "Gấp",
  offer_piority_very_urgent: "Rất gấp",
  number_offer: "Đề xuất",
  number_offer_aprroved: "Phê duyệt",
};

export const colors = {
  offer_of_me_sending: "#ff9800",
  offer_of_me_approved: "#03c30b",
  offer_status_approved: "#03c30b",
  offer_of_me_monitoring: "#f44336",
  offer_status_waiting: "#ff9800",
  offer_status_cancel: "#f44336",
  offer_piority_normal: "#ff9800",
  offer_piority_urgent: "#03c30b",
  offer_piority_very_urgent: "#f44336",
  number_offer: "#1155cc",
  number_offer_aprroved: "#ff9800",
};
export const action = {
  UPDATE_OFFER: "UPDATE_OFFER",
  CREATE_OFFER: "CREATE_OFFER",
  DELETE_GROUP_OFFER: "DELETE_GROUP_OFFER",
  HANDLE_OFFER: "HANDLE_OFFER"
}
