export const GET_LIST_COLUMNS = "ACTION_GET_LIST_COLUMNS";
export const GET_LIST_COLUMNS_SUCCESS = "ACTION_GET_LIST_COLUMNS_SUCCESS";
export const GET_LIST_COLUMNS_FAIL = "ACTION_GET_LIST_COLUMNS_FAIL";
export const GET_LIST_COLUMNS_RESET = "ACTION_GET_LIST_COLUMNS_RESET";
