// Update value Columns
export const UPDATE_VALUE_COLUMNS = "UPDATE_VALUE_COLUMNS";
export const UPDATE_VALUE_COLUMNS_SUCCESS = "UPDATE_VALUE_COLUMNS_SUCCESS";
export const UPDATE_VALUE_COLUMNS_FAIL = "UPDATE_VALUE_COLUMNS_FAIL";
