export const GET_PERMISSION_VIEW_USERS = 'ACTION_GET_PERMISSION_VIEW_USERS';
export const GET_PERMISSION_VIEW_USERS_SUCCESS = 'ACTION_GET_PERMISSION_VIEW_USERS_SUCCESS';
export const GET_PERMISSION_VIEW_USERS_FAIL = 'ACTION_GET_PERMISSION_VIEW_USERS_FAIL';
export const GET_PERMISSION_VIEW_PROJECTS = 'ACTION_GET_PERMISSION_VIEW_PROJECTS';
export const GET_PERMISSION_VIEW_PROJECTS_SUCCESS = 'ACTION_GET_PERMISSION_VIEW_PROJECTS_SUCCESS';
export const GET_PERMISSION_VIEW_PROJECTS_FAIL = 'ACTION_GET_PERMISSION_VIEW_PROJECTS_FAIL';
