export const GET_LIST_INVITATION_SENT = 'ACTION_GET_LIST_INVITATION_SENT';
export const GET_LIST_INVITATION_SENT_SUCCESS = 'ACTION_GET_LIST_INVITATION_SENT_SUCCESS';
export const GET_LIST_INVITATION_SENT_FAIL = 'ACTION_GET_LIST_INVITATION_SENT_FAIL';
export const GET_LIST_INVITATION_SENT_RESET = 'ACTION_GET_LIST_INVITATION_SENT_RESET';
