export const GET_REQUIREMENT_JOIN_GROUP = 'ACTION_GET_REQUIREMENT_JOIN_GROUP';
export const GET_REQUIREMENT_JOIN_GROUP_SUCCESS = 'ACTION_GET_REQUIREMENT_JOIN_GROUP_SUCCESS';
export const GET_REQUIREMENT_JOIN_GROUP_FAIL = 'ACTION_GET_REQUIREMENT_JOIN_GROUP_FAIL';
export const GET_REQUIREMENT_JOIN_GROUP_RESET = 'ACTION_GET_REQUIREMENT_JOIN_GROUP_RESET';
