export const BAN_USER_FROM_GROUP = 'ACTION_BAN_USER_FROM_GROUP';
export const BAN_USER_FROM_GROUP_SUCCESS = 'ACTION_BAN_USER_FROM_GROUP_SUCCESS';
export const BAN_USER_FROM_GROUP_FAIL = 'ACTION_BAN_USER_FROM_GROUP_FAIL';
