export const DELETE_DOCUMENTS_USER = 'ACTION_DELETE_DOCUMENTS_USER';
export const DELETE_DOCUMENTS_USER_SUCCESS = 'ACTION_DELETE_DOCUMENTS_USER_SUCCESS';
export const DELETE_DOCUMENTS_USER_FAIL = 'ACTION_DELETE_DOCUMENTS_USER_FAIL';
