export const DETAIL_USER = 'ACTION_DETAIL_USER';
export const DETAIL_USER_SUCCESS = 'ACTION_DETAIL_USER_SUCCESS';
export const DETAIL_USER_FAIL = 'ACTION_DETAIL_USER_FAIL';
export const DETAIL_USER_RESET = 'ACTION_DETAIL_USER_RESET';
export const CHECK_VERIFY_ACCOUNT = 'CHECK_VERIFY_ACCOUNT';
export const CHECK_VERIFY_ACCOUNT_SUCCESS = 'CHECK_VERIFY_ACCOUNT_SUCCESS';
export const CHECK_VERIFY_ACCOUNT_FAIL = 'CHECK_VERIFY_ACCOUNT_FAIL';
