export const INVITE_USER_JOIN_GROUP = 'ACTION_INVITE_USER_JOIN_GROUP';
export const INVITE_USER_JOIN_GROUP_SUCCESS = 'ACTION_INVITE_USER_JOIN_GROUP_SUCCESS';
export const INVITE_USER_JOIN_GROUP_FAIL = 'ACTION_INVITE_USER_JOIN_GROUP_FAIL';
