export const LIST_USER_OF_GROUP = 'ACTION_LIST_USER_OF_GROUP';
export const LIST_USER_OF_GROUP_SUCCESS = 'ACTION_LIST_USER_OF_GROUP_SUCCESS';
export const LIST_USER_OF_GROUP_FAIL = 'ACTION_LIST_USER_OF_GROUP_FAIL';
export const LIST_USER_OF_GROUP_RESET = 'ACTION_LIST_USER_OF_GROUP_RESET';
export const FILTER_LIST_USER_OF_GROUP_SUCCESS = 'ACTION_FILTER_LIST_USER_OF_GROUP_SUCCESS';
