export const PERMISSION_USER = 'ACTION_PERMISSION_USER';
export const PERMISSION_USER_SUCCESS = 'ACTION_PERMISSION_USER_SUCCESS';
export const PERMISSION_USER_FAIL = 'ACTION_PERMISSION_USER_FAIL';
export const PERMISSION_USER_RESET = 'ACTION_PERMISSION_USER_RESET';
