export const UPLOAD_DOCUMENTS_USER = 'ACTION_UPLOAD_DOCUMENTS_USER';
export const UPLOAD_DOCUMENTS_USER_SUCCESS = 'ACTION_UPLOAD_DOCUMENTS_USER_SUCCESS';
export const UPLOAD_DOCUMENTS_USER_FAIL = 'ACTION_UPLOAD_DOCUMENTS_USER_FAIL';
