export const LIST_MAJOR = 'ACTION_LIST_MAJOR';
export const LIST_MAJOR_SUCCESS = 'ACTION_LIST_MAJOR_SUCCESS';
export const LIST_MAJOR_FAIL = 'ACTION_LIST_MAJOR_FAIL';
export const LIST_MAJOR_RESET = 'ACTION_LIST_MAJOR_RESET';
