//Offer

export const GET_OFFER_REQUEST = 'GET_OFFER_REQUEST';
export const GET_OFFER_SUCCESS = 'GET_OFFER_SUCCESS';
export const GET_OFFER_FAIL = 'GET_OFFER_FAIL';

export const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST';
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const CREATE_OFFER_FAIL = 'CREATE_OFFER_FAIL';
// sub-task 
export const GET_SUBTASK_REQUEST = 'GET_SUBTASK_REQUEST'
export const GET_SUBTASK_SUCCESS = 'GET_SUBTASK_SUCCESS'
export const GET_SUBTASK_FAIL = 'GET_SUBTASK_FAIL'
