export const KANBAN_ADD_MANAGERS = 'ACTION_KANBAN_ADD_MANAGERS';
export const KANBAN_ADD_MANAGERS_SUCCESS = 'ACTION_KANBAN_ADD_MANAGERS_SUCCESS';
export const KANBAN_ADD_MANAGERS_FAIL = 'ACTION_KANBAN_ADD_MANAGERS_FAIL';
export const KANBAN_ADD_MANAGERS_RESET = 'ACTION_KANBAN_ADD_MANAGERS_RESET';
