export const KANBAN_DETAIL_PROJECT = 'ACTION_KANBAN_DETAIL_PROJECT';
export const KANBAN_DETAIL_PROJECT_SUCCESS = 'ACTION_KANBAN_DETAIL_PROJECT_SUCCESS';
export const KANBAN_DETAIL_PROJECT_FAIL = 'ACTION_KANBAN_DETAIL_PROJECT_FAIL';
export const KANBAN_DETAIL_PROJECT_RESET = 'ACTION_KANBAN_DETAIL_PROJECT_RESET';
