export const KANBAN_DETAIL_TASK = 'ACTION_KANBAN_DETAIL_TASK';
export const KANBAN_DETAIL_TASK_SUCCESS = 'ACTION_KANBAN_DETAIL_TASK_SUCCESS';
export const KANBAN_DETAIL_TASK_FAIL = 'ACTION_KANBAN_DETAIL_TASK_FAIL';
export const KANBAN_DETAIL_TASK_RESET = 'ACTION_KANBAN_DETAIL_TASK_RESET';
