export const KANBAN_GET_MANAGER = 'ACTION_KANBAN_GET_MANAGER';
export const KANBAN_GET_MANAGER_SUCCESS = 'ACTION_KANBAN_GET_MANAGER_SUCCESS';
export const KANBAN_GET_MANAGER_FAIL = 'ACTION_KANBAN_GET_MANAGER_FAIL';
export const KANBAN_GET_MANAGER_RESET = 'ACTION_KANBAN_GET_MANAGER_RESET';
