export const KANBAN_LIST_TASK = 'ACTION_KANBAN_LIST_TASK';
export const KANBAN_LIST_TASK_SUCCESS = 'ACTION_KANBAN_LIST_TASK_SUCCESS';
export const KANBAN_LIST_TASK_FAIL = 'ACTION_KANBAN_LIST_TASK_FAIL';
export const KANBAN_LIST_TASK_RESET = 'ACTION_KANBAN_LIST_TASK_RESET';
