export const KANBAN_REMOVE_MANAGERS = 'ACTION_KANBAN_REMOVE_MANAGERS';
export const KANBAN_REMOVE_MANAGERS_SUCCESS = 'ACTION_KANBAN_REMOVE_MANAGERS_SUCCESS';
export const KANBAN_REMOVE_MANAGERS_FAIL = 'ACTION_KANBAN_REMOVE_MANAGERS_FAIL';
export const KANBAN_REMOVE_MANAGERS_RESET = 'ACTION_KANBAN_REMOVE_MANAGERS_RESET';
