export const KANBAN_SORT_TASK = 'ACTION_KANBAN_SORT_TASK';
export const KANBAN_SORT_TASK_SUCCESS = 'ACTION_KANBAN_SORT_TASK_SUCCESS';
export const KANBAN_SORT_TASK_FAIL = 'ACTION_KANBAN_SORT_TASK_FAIL';
export const KANBAN_SORT_TASK_RESET = 'ACTION_KANBAN_SORT_TASK_RESET';
