export const KANBAN_SORT_GROUP_TASK = 'ACTION_KANBAN_SORT_GROUP_TASK';
export const KANBAN_SORT_GROUP_TASK_SUCCESS = 'ACTION_KANBAN_SORT_GROUP_TASK_SUCCESS';
export const KANBAN_SORT_GROUP_TASK_FAIL = 'ACTION_KANBAN_SORT_GROUP_TASK_FAIL';
export const KANBAN_SORT_GROUP_TASK_RESET = 'ACTION_KANBAN_SORT_GROUP_TASK_RESET';
