export const KANBAN_UPDATE_TASK = 'ACTION_KANBAN_UPDATE_TASK';
export const KANBAN_UPDATE_TASK_SUCCESS = 'ACTION_KANBAN_UPDATE_TASK_SUCCESS';
export const KANBAN_UPDATE_TASK_FAIL = 'ACTION_KANBAN_UPDATE_TASK_FAIL';
export const KANBAN_UPDATE_TASK_RESET = 'ACTION_KANBAN_UPDATE_TASK_RESET';
