export const KANBAN_UPDATE_MANAGERS = 'ACTION_KANBAN_UPDATE_MANAGERS';
export const KANBAN_UPDATE_MANAGERS_SUCCESS = 'ACTION_KANBAN_UPDATE_MANAGERS_SUCCESS';
export const KANBAN_UPDATE_MANAGERS_FAIL = 'ACTION_KANBAN_UPDATE_MANAGERS_FAIL';
export const KANBAN_UPDATE_MANAGERS_RESET = 'ACTION_KANBAN_UPDATE_MANAGERS_RESET';
