export const GANTT_SHOW_FULL_CHART = 'GANTT_SHOW_FULL_CHART';
export const GANTT_SHOW_HEADER = 'GANTT_SHOW_HEADER';
export const CHANGE_ROW_HOVER = 'CHANGE_ROW_HOVER';
export const CHANGE_TIMELINE_COLOR = 'CHANGE_TIMELINE_COLOR';
export const CHANGE_COLUMN_INDEX = 'CHANGE_COLUMN_INDEX';
export const CHANGE_VISIBLE = 'CHANGE_VISIBLE';


