export const GANTT_SHOW_FULL_CHART = "GANTT_SHOW_FULL_CHART";
export const GANTT_SHOW_HEADER = "GANTT_SHOW_HEADER";
export const CHANGE_ROW_HOVER = "CHANGE_ROW_HOVER";
export const CHANGE_TIMELINE_COLOR = "CHANGE_TIMELINE_COLOR";
export const CHANGE_COLUMN_INDEX = "CHANGE_COLUMN_INDEX";
export const CHANGE_VISIBLE = "CHANGE_VISIBLE";
export const CHANGE_CONTENT_PREVIEW_PDF = "CHANGE_CONTENT_PREVIEW_PDF";
export const CHANGE_RENDER_FULL_DAY = "CHANGE_RENDER_FULL_DAY";
export const CHANGE_FILTER_EXPORT_PDF = "CHANGE_FILTER_EXPORT_PDF";
export const CHANGE_INSTANCE_GIRD = "CHANGE_INSTANCE_GIRD";
export const CHANGE_PROJECT_INFO = "CHANGE_PROJECT_INFO";
export const CHANGE_TASK_DURATION = "CHANGE_TASK_DURATION";
export const SCROLL_GANTT = "SCROLL_GANTT";
export const CHANGE_SCHEDULE_DETAIL_GANTT = "CHANGE_SCHEDULE_DETAIL_GANTT";
export const CHANGE_PROJECT_SCHEDULE = "CHANGE_PROJECT_SCHEDULE";
export const FETCH_PROJECT_SCHEDULE = "FETCH_PROJECT_SCHEDULE";

