export const CREATE_PROJECT_GROUP = 'ACTION_CREATE_PROJECT_GROUP';
export const CREATE_PROJECT_GROUP_SUCCESS = 'ACTION_CREATE_PROJECT_GROUP_SUCCESS';
export const CREATE_PROJECT_GROUP_FAIL = 'ACTION_CREATE_PROJECT_GROUP_FAIL';
