export const DELETE_PROJECT_GROUP = 'ACTION_DELETE_PROJECT_GROUP';
export const DELETE_PROJECT_GROUP_SUCCESS = 'ACTION_DELETE_PROJECT_GROUP_SUCCESS';
export const DELETE_PROJECT_GROUP_FAIL = 'ACTION_DELETE_PROJECT_GROUP_FAIL';
