export const DETAIL_DEFAULT_GROUP = 'ACTION_DETAIL_DEFAULT_GROUP';
export const DETAIL_DEFAULT_GROUP_SUCCESS = 'ACTION_DETAIL_DEFAULT_GROUP_SUCCESS';
export const DETAIL_DEFAULT_GROUP_FAIL = 'ACTION_DETAIL_DEFAULT_GROUP_FAIL';
export const DETAIL_DEFAULT_GROUP_RESET = 'ACTION_DETAIL_DEFAULT_GROUP_RESET';
