export const DETAIL_PROJECT_GROUP = 'ACTION_DETAIL_PROJECT_GROUP';
export const DETAIL_PROJECT_GROUP_SUCCESS = 'ACTION_DETAIL_PROJECT_GROUP_SUCCESS';
export const DETAIL_PROJECT_GROUP_FAIL = 'ACTION_DETAIL_PROJECT_GROUP_FAIL';
export const DETAIL_PROJECT_GROUP_RESET = 'ACTION_DETAIL_PROJECT_GROUP_RESET';
