export const EDIT_PROJECT_GROUP = 'ACTION_EDIT_PROJECT_GROUP';
export const EDIT_PROJECT_GROUP_SUCCESS = 'ACTION_EDIT_PROJECT_GROUP_SUCCESS';
export const EDIT_PROJECT_GROUP_FAIL = 'ACTION_EDIT_PROJECT_GROUP_FAIL';
