export const LIST_PROJECT_GROUP = 'ACTION_LIST_PROJECT_GROUP';
export const LIST_PROJECT_GROUP_SUCCESS = 'ACTION_LIST_PROJECT_GROUP_SUCCESS';
export const LIST_PROJECT_GROUP_FAIL = 'ACTION_LIST_PROJECT_GROUP_FAIL';
export const LIST_PROJECT_GROUP_RESET = 'ACTION_LIST_PROJECT_GROUP_RESET';
