export const MEMBER_PROJECT_GROUP = 'ACTION_MEMBER_PROJECT_GROUP';
export const MEMBER_PROJECT_GROUP_SUCCESS = 'ACTION_MEMBER_PROJECT_GROUP_SUCCESS';
export const MEMBER_PROJECT_GROUP_FAIL = 'ACTION_MEMBER_PROJECT_GROUP_FAIL';
export const MEMBER_PROJECT_GROUP_RESET = 'ACTION_MEMBER_PROJECT_GROUP_RESET';
