export const SORT_PROJECT_GROUP = 'ACTION_SORT_PROJECT_GROUP';
export const SORT_PROJECT_GROUP_SUCCESS = 'ACTION_SORT_PROJECT_GROUP_SUCCESS';
export const SORT_PROJECT_GROUP_FAIL = 'ACTION_SORT_PROJECT_GROUP_FAIL';
