export const TASK_OVERVIEW = "task.overview";
export const LOAD_TASK_OVERVIEW = "loadpage_task.overview";
export const TASK_OVERVIEW_STATISTIC = "task.overview.statistic";
export const TASK_OVERVIEW_RECENT = "task.overview.recent";
export const LOADPAGE_TASK = "task";
export const LOADPAGE_TASK_DUE = "loadpage_task.due";
export const TASK_DUE = "task.due";
export const TASK_EXPIRED = "task.expired";
export const TASK_WAITING = "task.waiting";
export const TASK_COMPLETE = "task.complete";
export const TASK_DOING = "task.doing";
export const TASK_STOP = "task.stop";
export const LOADPAGE_TASK_ASSIGN = "loadpage_task.assign";
export const TASK_ASSIGN = "task.assign";
export const LOADPAGE_TASK_ROLE = "loadpage_task.role";
export const TASK_ROLE = "task.role";
//
export const TASK_RECENTLY = "TASK_RECENTLY";
export const LOAD_TASK_RENCENTLY = "LOAD_TASK_RECENTLY";
export const LOAD_TASK_RECENTLY_SUCCESS = "LOAD_TASK_RECENTLY_SUCCESS";
//
export const SUMMARY_BY_GROUP = "SUMMARY_BY_GROUP";
export const LOAD_SUMMARY_BY_GROUP = "LOAD_SUMMARY_BY_GROUP";
export const LOAD_SUMMARY_BY_GROUP_SUCCESS = "LOAD_SUMMARY_BY_GROUP_SUCCESS";
//
export const CREATE_GROUP_OFFER = "CREATE_OFFER_GROUP";
export const CREATE_GROUP_OFFER_SUCCESS = "CREATE_OFFER_GROUP_SUCCESS";
export const CREATE_GROUP_OFFER_ERROR = "CREATE_OFFER_GROUP_ERROR";
//
export const LOAD_OFFER_BY_GROUP_ID = "LOAD_OFFER_BY_GROUP_ID";
export const LOAD_OFFER_BY_GROUP_ID_SUCCESS = "LOAD_OFFER_BY_GROUP_ID_SUCCESS";
//
export const OFFER_BY_GROUP = "OFFER_BY_GROUP";
export const OFFER_BY_DEPARTMENT = "OFFER_BY_DEPARTMENT";
//
export const TASK_OFFER_BY_DEPARTMENT = "TASK_OFFER_BY_DEPARTMENT";
export const LOAD_SUMMARY_BY_DEPARTMENT_SUCCESS = "LOAD_OFFER_BY_DEPEARTMENT_SUCCESS"
export const LOAD_SUMMARY_DEPARTMENT = "LOAD_OFFER_BY_DEPARTMENT"
export const LOAD_OFFER_BY_DEPARTMENT_ID_SUCCESS = "LOAD_OFFER_BY_DEPEARTMENT_SUCCESS"
export const LOAD_OFFER_BY_DEPARTMENT_ID = "LOAD_OFFER_BY_DEPARTMENT"

// 
export const SUMMARY_OVERVIEW = "SUMMARY_OVERVIEW"
export const LOAD_SUMMARY_OVERVIEW = "LOAD_SUMMARY_OVERVIEW"
export const LOAD_SUMMARY_OVERVIEW_SUCCESS = "LOAD_SUMMARY_OVERVIEW_SUCCESS"

// Tạo group offer
export const DELETE_GROUP_OFFER = "DELETE_GROUP_OFFER"
export const DELETE_GROUP_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS"
export const DELETE_GROUP_OFFER_ERROR = "DELETE_OFFER_ERROR"
// Chỉnh sửa group offer
export const UPDATE_GROUP_OFFER_OFFERPAGE = "UPDATE_GROUP_OFFER_OFFERPAGE"
export const UPDATE_GROUP_OFFER_OFFERPAGE_SUCCESS = "UPDATE_GROUP_OFFER_OFFERPAGE_SUCCESS"
export const UPDATE_GROUP_OFFER_OFFERPAGE_ERROR = "UPDATE_GROUP_OFFER_OFFERPAGE_ERROR"
//
export const DETAIL_OFFER = "DETAIL_OFFER"
export const LOAD_DETAIL_OFFER = "DETAIL_OFFER"
export const LOAD_DETAIL_OFFER_SUCCESS = "DETAIL_OFFER_SUCCESS"
export const LOAD_DETAIL_OFFER_ERROR = "DETAIL_OFFER_ERROR"
export const DELETE_OFFER = "DELETE_OFFER"
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS"
export const DELETE_OFFER_ERROR = "DELETE_OFFER_ERROR"

//
export const UPLOAD_DOCUMENT_OFFER = "UPLOAD_DOCUMENT_OFFER"
export const UPLOAD_DOCUMENT_OFFER_SUCCESS = "UPLOAD_DOCUMENT_OFFER_SUCCESS"
export const UPLOAD_DOCUMENT_OFFER_ERROR = "UPLOAD_DOCUMENT_OFFER_ERROR"

export const DELETE_DOCUMENT_OFFER = "DELETE_DOCUMENT_OFFER"
export const DELETE_DOCUMENT_OFFER_SUCCESS = "DELETE_DOCUMENT_OFFER_SUCCESS"
export const DELETE_DOCUMENT_OFFER_ERROR = "DELETE_DOCUMENT_OFFER_ERROR"
//

export const ADD_MEMBER_HANDLE = "ADD_MEMBER_HANDLE"
export const ADD_MEMBER_HANDLE_SUCCESS = "ADD_MEMBER_HANDLE_SUCCESS"
export const ADD_MEMBER_HANDLE_ERROR = "ADD_MEMBER_HANDLE_ERROR"
//

export const DELETE_MEMBER_HANDLE = "DELETE_MEMBER_HANDLE"
export const DELETE_MEMBER_HANDLE_SUCCESS = "DELETE_MEMBER_HANDLE_SUCCESS"
export const DELETE_MEMBER_HANDLE_ERROR = "DELETE_MEMBER_HANDLE_ERROR"
//
export const ADD_MEMBER_MONITOR = "ADD_MEMBER_MONITOR"
export const ADD_MEMBER_MONITOR_SUCCESS = "ADD_MEMBER_MONITOR_SUCCESS"
export const ADD_MEMBER_MONITOR_ERROR = "ADD_MEMBER_MONITOR_ERROR"
export const RESET_ADD_MEMBER_MONITOR = "RESET_MEMBER_MONITOR"
//

export const DELETE_MEMBER_MONITOR = "DELETE_MEMBER_MONITOR"
export const DELETE_MEMBER_MONITOR_SUCCESS = "DELETE_MEMBER_MONITOR_SUCCESS"
export const DELETE_MEMBER_MONITOR_ERROR = "DELETE_MEMBER_MONITOR_ERROR"
export const RESET_DELETE_MEMBER_MONOTOR = "RESET_DELETE_MEMBER_MONOTOR"
///
export const HANDLE_OFFER_OFFERPAGE = "HANDLE_OFFER_OFFERPAGE"
export const HANDLE_OFFER_OFFERPAGE_SUCCESS = "HANDLE_OFFER_OFFERPAGE_SUCCESS"
export const HANDLE_OFFER_OFFERPAGE_ERROR = "HANDLE_OFFER_OFFERPAGE_ERROR"
// Load summary project cột trái
export const SUMMARY_PROJECT = "SUMMARY_PROJECT"
export const LOAD_SUMMARY_BY_PROJECT = "LOAD_SUMMARY_BY_PROJECT"
export const LOAD_SUMMARY_BY_PROJECT_SUCCESS = "LOAD_SUMMARY_BY_PROJECT_SUCCESS"
export const LOAD_SUMMARY_BY_PROJECT_ERROR = "LOAD_SUMMARY_BY_PROJECT_ERROR"
// Load offer theo project id
export const LOAD_OFFER_BY_PROJECT_ID = "LOAD_OFFER_BY_PROJECT_ID"
export const LOAD_OFFER_BY_PROJECT_ID_SUCCESS = "LOAD_OFFER_BY_PROJECT_ID_SUCCESS"
export const LOAD_OFFER_BY_PROJECT_ID_ERROR = "LOAD_OFFER_BY_PROJECT_ID_ERROR"
export const OFFER_BY_PROJECT = "OFFER_PROJECT"
///
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
//
export const NOTIFICATIONS = 'NOTIFICATIONS'