export const LIST_PERSONAL_REMIND_CATEGORY = "ACTION_LIST_PERSIONAL_REMIND_CATEGORY";
export const LIST_PERSONAL_REMIND_CATEGORY_FAIL = "ACTION_LIST_PERSIONAL_REMIND_CATEGORY_FAIL";
export const LIST_PERSONAL_REMIND_CATEGORY_SUCCESS = "ACTION_LIST_PERSIONAL_REMIND_CATEGORY_SUCCESS";

export const SORT_PERSONAL_REMIND_CATEGORY = "ACTION_SORT_PERSONAL_REMIND_CATEGORY";
export const SORT_PERSONAL_REMIND_CATEGORY_SUCCESS = "ACTION_SORT_PERSONAL_REMIND_CATEGORY_SUCCESS";
export const SORT_PERSONAL_REMIND_CATEGORY_FAIL = "ACTION_SORT_PERSONAL_REMIND_CATEGORY_FAIL";

export const LIST_PERSONAL_REMIND = "ACTION_LIST_PERSONAL_REMIND";
export const LIST_PERSONAL_REMIND_SUCCESS = "ACTION_LIST_PERSONAL_REMIND_SUCCESS";
export const LIST_PERSONAL_REMIND_FAIL = "ACTION_LIST_PERSONAL_REMIND_FAIL";

export const CREATE_PERSONAL_REMIND = "ACTION_CREATE_PERSONAL_REMIND";
export const CREATE_PERSONAL_REMIND_SUCCESS = "ACTION_CREATE_PERSONAL_REMIND_SUCCESS";
export const CREATE_PERSONAL_REMIND_FAIL = "ACTION_CREATE_PERSONAL_REMIND_FAIL";

export const UPDATE_PERSONAL_REMIND = "ACTION_UPDATE_PERSONAL_REMIND";
export const UPDATE_PERSONAL_REMIND_SUCCESS = "ACTION_UPDATE_PERSONAL_REMIND_SUCCESS";
export const UPDATE_PERSONAL_REMIND_FAIL = "ACTION_UPDATE_PERSONAL_REMIND_FAIL";

export const DELETE_PERSONAL_REMIND = "ACTION_DELETE_PERSONAL_REMIND";
export const DELETE_PERSONAL_REMIND_SUCCESS = "ACTION_DELETE_PERSONAL_REMIND_SUCCESS";
export const DELETE_PERSONAL_REMIND_FAIL = "ACTION_DELETE_PERSONAL_REMIND_FAIL";

export const LIST_REMIND_RECENTLY = "ACTION_LIST_REMIND_RECENTLY";
export const LIST_REMIND_RECENTLY_SUCCESS = "ACTION_LIST_REMIND_RECENTLY_SUCCESS";
export const LIST_REMIND_RECENTLY_FAIL = "ACTION_LIST_REMIND_RECENTLY_FAIL";

export const CREATE_PERSONAL_CATEGORY_REMIND = "ACTION_CREATE_PERSONAL_CATEGORY_REMIND";
export const CREATE_PERSONAL_CATEGORY_REMIND_SUCCESS = "ACTION_CREATE_PERSONAL_CATEGORY_REMIND_SUCCESS";
export const CREATE_PERSONAL_CATEGORY_REMIND_FAIL = "ACTION_CREATE_PERSONAL_CATEGORY_REMIND_FAIL";

export const UPDATE_PERSONAL_CATEGORY_REMIND = "ACTION_UPDATE_PERSONAL_CATEGORY_REMIND";
export const UPDATE_PERSONAL_CATEGORY_REMIND_SUCCESS = "ACTION_UPDATE_PERSONAL_CATEGORY_REMIND_SUCCESS";
export const UPDATE_PERSONAL_CATEGORY_REMIND_FAIL = "ACTION_UPDATE_PERSONAL_CATEGORY_REMIND_FAIL";

export const DELETE_PERSONAL_CATEGORY_REMIND = "ACTION_DELETE_PERSONAL_CATEGORY_REMIND";
export const DELETE_PERSONAL_CATEGORY_REMIND_SUCCESS = "ACTION_DELETE_PERSONAL_CATEGORY_REMIND_SUCCESS";
export const DELETE_PERSONAL_CATEGORY_REMIND_FAIL = "ACTION_DELETE_PERSONAL_CATEGORY_REMIND_FAIL";

export const LIST_REMIND_PROJECT = "ACTION_LIST_REMIND_PROJECT";
export const LIST_REMIND_PROJECT_SUCCESS = "ACTION_LIST_REMIND_PROJECT_SUCCESS";
export const LIST_REMIND_PROJECT_FAIL = "ACTION_LIST_REMIND_PROJECT_FAIL";

export const GET_REMIND_DETAIL = "ACTION_GET_REMIND_DETAIL";
export const GET_REMIND_DETAIL_SUCCESS = "ACTION_GET_REMIND_DETAIL_SUCCESS";
export const GET_REMIND_DETAIL_FAIL = "ACTION_GET_REMIND_DETAIL_FAIL";