import { takeLatest } from 'redux-saga/effects';
import { LOGIN, LOGIN_CHECK_STATE } from '../constants/actions/authentications';
import { login, loginCheckState } from './authentications';
import { LIST_ROOM } from '../constants/actions/room/listRoom';
import { listRoom } from './room/listRoom';
import { DETAIL_ROOM } from '../constants/actions/room/detailRoom';
import { detailRoom } from './room/detailRoom';
import { GET_USER_OF_ROOM } from '../constants/actions/room/getUserOfRoom';
import { getUserOfRoom } from './room/getUserOfRoom';
import { LIST_USER_OF_GROUP } from '../constants/actions/user/listUserOfGroup';
import { listUserOfGroup } from './user/listUserOfGroup';
import { SORT_USER } from '../constants/actions/user/sortUser';
import { sortUser } from './user/sortUser';
import { LIST_ICON } from '../constants/actions/icon/listIcon';
import { listIcon } from './icon/listIcon';
import { CREATE_ROOM } from '../constants/actions/room/createRoom';
import { createRoom } from './room/createRoom';
import { DELETE_ROOM } from '../constants/actions/room/deleteRoom';
import { deleteRoom } from './room/deleteRoom';
import { UPDATE_ROOM } from '../constants/actions/room/updateRoom';
import { updateRoom } from './room/updateRoom';
import { SORT_ROOM } from '../constants/actions/room/sortRoom';
import { sortRoom } from './room/sortRoom';
import { DETAIL_USER } from '../constants/actions/user/detailUser';
import { detailUser } from './user/detailUser';
import { UPLOAD_DOCUMENTS_USER } from '../constants/actions/user/uploadDocumentsUser';
import { uploadDocumentsUser } from './user/uploadDocumentsUser';
import { LIST_MAJOR } from '../constants/actions/major/listMajor';
import { listMajor } from './major/listMajor';
import { LIST_LEVEL } from '../constants/actions/level/listLevel';
import { listLevel } from './level/listLevel';
import { LIST_POSITION } from '../constants/actions/position/listPosition';
import { listPosition } from './position/listPosition';
import { UPDATE_USER } from '../constants/actions/user/updateUser';
import { updateUser } from './user/updateUser';
import { CREATE_POSITION } from '../constants/actions/position/createPosition';
import { createPosition } from './position/createPosition';
import { UPDATE_POSITION } from '../constants/actions/position/updatePosition';
import { updatePosition } from './position/updatePosition';
import { DELETE_POSITION } from '../constants/actions/position/deletePosition';
import { deletePosition } from './position/deletePosition';
import { LIST_USER_ROLE } from '../constants/actions/userRole/listUserRole';
import { listUserRole } from './userRole/listUserRole';
import { CREATE_USER_ROLE } from '../constants/actions/userRole/createUserRole';
import { createUserRole } from './userRole/createUserRole';
import { UPDATE_USER_ROLE } from '../constants/actions/userRole/updateUserRole';
import { updateUserRole } from './userRole/updateUserRole';
import { DELETE_USER_ROLE } from '../constants/actions/userRole/deleteUserRole';
import { deleteUserRole } from './userRole/deleteUserRole';

function* rootSaga() {
  yield takeLatest(LOGIN, login);
  yield takeLatest(LOGIN_CHECK_STATE, loginCheckState);
  yield takeLatest(LIST_ROOM, listRoom);
  yield takeLatest(DETAIL_ROOM, detailRoom);
  yield takeLatest(GET_USER_OF_ROOM, getUserOfRoom);
  yield takeLatest(LIST_USER_OF_GROUP, listUserOfGroup);
  yield takeLatest(SORT_USER, sortUser);
  yield takeLatest(LIST_ICON, listIcon);
  yield takeLatest(CREATE_ROOM, createRoom);
  yield takeLatest(DELETE_ROOM, deleteRoom);
  yield takeLatest(UPDATE_ROOM, updateRoom);
  yield takeLatest(SORT_ROOM, sortRoom);
  yield takeLatest(DETAIL_USER, detailUser);
  yield takeLatest(UPLOAD_DOCUMENTS_USER, uploadDocumentsUser);
  yield takeLatest(LIST_MAJOR, listMajor);
  yield takeLatest(LIST_LEVEL, listLevel);
  yield takeLatest(LIST_POSITION, listPosition);
  yield takeLatest(UPDATE_USER, updateUser);
  yield takeLatest(CREATE_POSITION, createPosition);
  yield takeLatest(UPDATE_POSITION, updatePosition);
  yield takeLatest(DELETE_POSITION, deletePosition);
  yield takeLatest(LIST_USER_ROLE, listUserRole);
  yield takeLatest(CREATE_USER_ROLE, createUserRole);
  yield takeLatest(UPDATE_USER_ROLE, updateUserRole);
  yield takeLatest(DELETE_USER_ROLE, deleteUserRole);
};

export default rootSaga;
