export const GET_USER_OF_ROOM = 'ACTION_GET_USER_OF_ROOM';
export const GET_USER_OF_ROOM_SUCCESS = 'ACTION_GET_USER_OF_ROOM_SUCCESS';
export const GET_USER_OF_ROOM_FAIL = 'ACTION_GET_USER_OF_ROOM_FAIL';
export const GET_USER_OF_ROOM_RESET = 'ACTION_GET_USER_OF_ROOM_RESET';
export const FILTER_USER_OF_GROUP_SUCCESS = 'FILTER_USER_OF_GROUP_SUCCESS';
