export const CHANGE_DRAWER = 'CHANGE_DRAWER';
export const CHANGE_NOTICE_MODAL = 'CHANGE_NOTICE_MODAL';
export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL';
export const CHANGE_SETTING_ACCOUNT = 'CHANGE_SETTING_ACCOUNT';
export const CHANGE_SETTING_GROUP = 'CHANGE_SETTING_GROUP';
export const SELECTED_NOTIFICATION = 'SELECTED_NOTIFICATION';
export const CHANGE_BACKGROUND_MENU = 'CHANGE_BACKGROUND_MENU';
export const CHANGE_DOCUMENT_DETAIL = 'CHANGE_DOCUMENT_DETAIL';
export const CHANGE_DOCUMENT_BREAD_CRUMBS = 'CHANGE_DOCUMENT_BREAD_CRUMBS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const ACTION_TOAST = 'ACTION_TOAST';
export const CHANGE_NUM_NOTIFICATION_NOT_VIEW = 'CHANGE_NUM_NOTIFICATION_NOT_VIEW';
export const CHANGE_NUM_MESSAGE_NOT_VIEW = 'CHANGE_NUM_MESSAGE_NOT_VIEW';
export const GROUP_ACTIVE = 'GROUP_ACTIVE';
export const COLOR_ACTIVE = 'COLOR_ACTIVE';
export const CHANGE_VISIBLE_COMMON_CONFIG = 'CHANGE_VISIBLE_COMMON_CONFIG';
export const CHANGE_VISIBLE_EXPORT_PDF_DRAWER = 'CHANGE_VISIBLE_EXPORT_PDF_DRAWER';
export const CHANGE_VISIBLE_SUBTASK_DRAWER = 'CHANGE_VISIBLE_SUBTASK_DRAWER';
export const CHANGE_DETAIL_SUBTASK_DRAWER = 'CHANGE_DETAIL_SUBTASK_DRAWER';
export const CHANGE_VISIBLE_OFFER_DETAIL_MODAL = "CHANGE_VISIBLE_OFFER_DETAIL_MODAL";
export const CHANGE_VISIBLE_REMIND_DETAIL_MODAL = "CHANGE_VISIBLE_REMIND_DETAIL_MODAL";
export const SET_NUMBER_DISCUSTION_NOT_VIEW = "SET_NUMBER_DISCUSTION_NOT_VIEW";


