export const CREATE_PROJECT_LABELS = "CREATE_PROJECT_LABELS";
export const CREATE_PROJECT_LABELS_SUCCESS = "CREATE_PROJECT_LABELS_SUCCESS";
export const CREATE_PROJECT_LABELS_FAIL = "CREATE_PROJECT_LABELS_FAIL";
