export const EDIT_PROJECT_LABELS = "EDIT_PROJECT_LABELS";
export const EDIT_PROJECT_LABELS_SUCCESS = "EDIT_PROJECT_LABELS_SUCCESS";
export const EDIT_PROJECT_LABELS_FAIL = "EDIT_PROJECT_LABELS_FAIL";
