export const LIST_PROJECT_LABEL = "ACTION_LIST_PROJECT_LABEL";
export const LIST_PROJECT_LABEL_SUCCESS = "ACTION_LIST_PROJECT_LABEL_SUCCESS";
export const LIST_PROJECT_LABEL_FAIL = "ACTION_LIST_PROJECT_LABEL_FAIL";
