export const LIST_POSITION = 'ACTION_LIST_POSITION';
export const LIST_POSITION_SUCCESS = 'ACTION_LIST_POSITION_SUCCESS';
export const LIST_POSITION_FAIL = 'ACTION_LIST_POSITION_FAIL';
export const LIST_POSITION_RESET = 'ACTION_LIST_POSITION_RESET';
