export const ADD_MEMBER_PROJECT = 'ACTION_ADD_MEMBER_PROJECT';
export const ADD_MEMBER_PROJECT_SUCCESS = 'ACTION_ADD_MEMBER_PROJECT_SUCCESS';
export const ADD_MEMBER_PROJECT_FAIL = 'ACTION_ADD_MEMBER_PROJECT_FAIL';
