export const ADD_PROJECT_ROLE_TO_MEMBER = 'ACTION_ADD_PROJECT_ROLE_TO_MEMBER';
export const ADD_PROJECT_ROLE_TO_MEMBER_SUCCESS = 'ACTION_ADD_PROJECT_ROLE_TO_MEMBER_SUCCESS';
export const ADD_PROJECT_ROLE_TO_MEMBER_FAIL = 'ACTION_ADD_PROJECT_ROLE_TO_MEMBER_FAIL';
