export const ASSIGN_MEMBER_TO_ALL_TASK = 'ACTION_ASSIGN_MEMBER_TO_ALL_TASK';
export const ASSIGN_MEMBER_TO_ALL_TASK_SUCCESS = 'ACTION_ASSIGN_MEMBER_TO_ALL_TASK_SUCCESS';
export const ASSIGN_MEMBER_TO_ALL_TASK_FAIL = 'ACTION_ASSIGN_MEMBER_TO_ALL_TASK_FAIL';
