export const DELETE_TRASH_PROJECT = 'ACTION_DELETE_TRASH_PROJECT';
export const DELETE_TRASH_PROJECT_SUCCESS = 'ACTION_DELETE_TRASH_PROJECT_SUCCESS';
export const DELETE_TRASH_PROJECT_FAIL = 'ACTION_DELETE_TRASH_PROJECT_FAIL';
