export const DETAIL_PROJECT = 'ACTION_DETAIL_PROJECT';
export const DETAIL_PROJECT_SUCCESS = 'ACTION_DETAIL_PROJECT_SUCCESS';
export const DETAIL_PROJECT_FAIL = 'ACTION_DETAIL_PROJECT_FAIL';
export const DETAIL_PROJECT_RESET = 'ACTION_DETAIL_PROJECT_RESET';
