export const GET_ALL_TEMPLATE = "ACTION_GET_ALL_TEMPLATE";
export const GET_ALL_TEMPLATE_SUCCESS = "ACTION_GET_ALL_TEMPLATE_SUCCESS";
export const GET_ALL_TEMPLATE_FAIL = "ACTION_GET_ALL_TEMPLATE_FAIL";
