export const GET_DETAIL_TEMPLATE = "ACTION_GET_DETAIL_TEMPLATE";
export const GET_DETAIL_TEMPLATE_SUCCESS = "ACTION_GET_DETAIL_TEMPLATE_SUCCESS";
export const GET_DETAIL_TEMPLATE_FAIL = "ACTION_GET_DETAIL_TEMPLATE_FAIL";
