export const GET_LIST_TEMPLATE_ME_SHARED = "ACTION_GET_LIST_TEMPLATE_ME_SHARED";
export const GET_LIST_TEMPLATE_ME_SHARED_SUCCESS =
  "ACTION_GET_LIST_TEMPLATE_ME_SHARED_SUCCESS";
export const GET_LIST_TEMPLATE_ME_SHARED_FAIL =
  "ACTION_GET_LIST_TEMPLATE_ME_SHARED_FAIL";
