export const GET_LIST_TEMPLATE = "ACTION_GET_LIST_TEMPLATE";
export const GET_LIST_TEMPLATE_SUCCESS = "ACTION_GET_LIST_TEMPLATE_SUCCESS";
export const GET_LIST_TEMPLATE_FAIL = "ACTION_GET_LIST_TEMPLATE_FAIL";
