export const GET_NEWEST_TEMPLATE = "ACTION_GET_NEWEST_TEMPLATE";
export const GET_NEWEST_TEMPLATE_SUCCESS = "ACTION_GET_NEWEST_TEMPLATE_SUCCESS";
export const GET_NEWEST_TEMPLATE_FAIL = "ACTION_GET_NEWEST_TEMPLATE_FAIL";
