export const GET_PROJECT_STATISTIC = 'ACTION_GET_PROJECT_STATISTIC';
export const GET_PROJECT_STATISTIC_SUCCESS = "ACTION_GET_PROJECT_STATISTIC_SUCCESS";
export const GET_GET_PROJECT_STATISTIC_FAIL = "ACTION_GET_PROJECT_STATISTIC_FAIL";