export const GET_PROJECT_STATUS_WORK = 'ACTION_GET_PROJECT_STATUS_WORK';
export const GET_PROJECT_STATUS_WORK_SUCCESS = "ACTION_GET_PROJECT_STATUS_WORK_SUCCESS";
export const GET_PROJECT_STATUS_WORK_FAIL = "ACTION_GET_PROJECT_STATUS_WORK_FAIL";