export const GET_TEMPLATE_BY_CATEGORY = "ACTION_GET_TEMPLATE_BY_CATEGORY";
export const GET_TEMPLATE_BY_CATEGORY_SUCCESS =
  "ACTION_GET_TEMPLATE_BY_CATEGORY_SUCCESS";
export const GET_TEMPLATE_BY_CATEGORY_FAIL =
  "ACTION_GET_TEMPLATE_BY_CATEGORY_FAIL";
