export const GET_TEMPLATE_CATEGORY = "ACTION_GET_TEMPLATE_CATEGORY";
export const GET_TEMPLATE_CATEGORY_SUCCESS =
  "ACTION_GET_TEMPLATE_CATEGORY_SUCCESS";
export const GET_TEMPLATE_CATEGORY_FAIL = "ACTION_GET_TEMPLATE_CATEGORY_FAIL";
