export const LIST_PROJECT_BASIC_INFO = 'ACTION_LIST_PROJECT_BASIC_INFO';
export const LIST_PROJECT_BASIC_INFO_SUCCESS = 'ACTION_LIST_PROJECT_BASIC_INFO_SUCCESS';
export const LIST_PROJECT_BASIC_INFO_FAIL = 'ACTION_LIST_PROJECT_BASIC_INFO_FAIL';