export const LIST_DELETED_PROJECT = 'ACTION_LIST_DELETED_PROJECT';
export const LIST_DELETED_PROJECT_SUCCESS = 'ACTION_LIST_DELETED_PROJECT_SUCCESS';
export const LIST_DELETED_PROJECT_FAIL = 'ACTION_LIST_DELETED_PROJECT_FAIL';
