export const LIST_PROJECT = 'ACTION_LIST_PROJECT';
export const LIST_PROJECT_SUCCESS = 'ACTION_LIST_PROJECT_SUCCESS';
export const LIST_PROJECT_FAIL = 'ACTION_LIST_PROJECT_FAIL';
export const LIST_PROJECT_RESET = 'ACTION_LIST_PROJECT_RESET';
