export const PERMISSION_PROJECT = 'ACTION_PERMISSION_PROJECT';
export const PERMISSION_PROJECT_SUCCESS = 'ACTION_PERMISSION_PROJECT_SUCCESS';
export const PERMISSION_PROJECT_FAIL = 'ACTION_PERMISSION_PROJECT_FAIL';
export const PERMISSION_PROJECT_RESET = 'ACTION_PERMISSION_PROJECT_RESET';
