export const GET_PROJECTS_RECENTLY = 'ACTION_GET_PROJECTS_RECENTLY';
export const GET_PROJECTS_RECENTLY_SUCCESS = "ACTION_GET_PROJECTS_RECENTLY_SUCCESS";
export const GET_PROJECTS_RECENTLY_FAIL = "ACTION_GET_PROJECTS_RECENTLY_FAIL";