export const REMOVE_MEMBER_PROJECT = 'ACTION_REMOVE_MEMBER_PROJECT';
export const REMOVE_MEMBER_PROJECT_SUCCESS = 'ACTION_REMOVE_MEMBER_PROJECT_SUCCESS';
export const REMOVE_MEMBER_PROJECT_FAIL = 'ACTION_REMOVE_MEMBER_PROJECT_FAIL';
