export const RESTORE_TRASH_PROJECT = 'ACTION_RESTORE_TRASH_PROJECT';
export const RESTORE_TRASH_PROJECT_SUCCESS = 'ACTION_RESTORE_TRASH_PROJECT_SUCCESS';
export const RESTORE_TRASH_PROJECT_FAIL = 'ACTION_RESTORE_TRASH_PROJECT_FAIL';
