export const SEARCH_TEMPLATE = "ACTION_SEARCH_TEMPLATE";
export const SEARCH_TEMPLATE_SUCCESS = "ACTION_SEARCH_TEMPLATE_SUCCESS";
export const SEARCH_TEMPLATE_FAIL = "ACTION_SEARCH_TEMPLATE_FAIL";
export const SEARCH_TEMPLATE_RESET = "ACTION_SEARCH_TEMPLATE_RESET";
