export const UPDATE_STATE_JOIN_TASK = 'ACTION_UPDATE_STATE_JOIN_TASK';
export const UPDATE_STATE_JOIN_TASK_SUCCESS = 'ACTION_UPDATE_STATE_JOIN_TASK_SUCCESS';
export const UPDATE_STATE_JOIN_TASK_FAIL = 'ACTION_UPDATE_STATE_JOIN_TASK_FAIL';
