export const CHANGE_TAB = 'CHANGE_TAB';
export const FILTER_DOCUMENTS = 'ACTION_FILTER_DOCUMENTS';
export const SET_ALL_DATA_DOCUMENTS = 'SET_ALL_DATA_DOCUMENTS';
export const SELECT_DOCUMENT_ITEM = 'SELECT_DOCUMENT_ITEM';
export const RESET_LIST_SELECT_DOCUMENT = 'RESET_LIST_SELECT_DOCUMENT';
