export const CHANGE_TAB = 'CHANGE_TAB';
export const FILTER_DOCUMENTS = 'ACTION_FILTER_DOCUMENTS';
export const SET_ALL_DATA_DOCUMENTS = 'SET_ALL_DATA_DOCUMENTS';
export const SELECT_DOCUMENT_ITEM = 'SELECT_DOCUMENT_ITEM';
export const RESET_LIST_SELECT_DOCUMENT = 'RESET_LIST_SELECT_DOCUMENT';
export const DOCUMENT_HIDE_LOADING = 'DOCUMENT_HIDE_LOADING';
export const LIST_COMMENT = 'ACTION_LIST_COMMENT';
export const LIST_COMMENT_SUCCESS = 'ACTION_LIST_COMMENT_SUCCESS';
export const LIST_TRASH = 'ACTION_LIST_TRASH';
export const LIST_TRASH_SUCCESS = 'ACTION_LIST_TRASH_SUCCESS';
export const LIST_MY_DOCUMENT = 'ACTION_LIST_MY_DOCUMENT';
export const LIST_MY_DOCUMENT_SUCCESS = 'ACTION_LIST_MY_DOCUMENT_SUCCESS';
export const ACTION_SELECTED_FOLDER = 'ACTION_SELECTED_FOLDER';
export const LIST_RECENT = 'ACTION_LIST_RECENT';
export const LIST_RECENT_SUCCESS = 'ACTION_LIST_RECENT_SUCCESS';
export const LIST_PROJECT_DOCUMENT = 'ACTION_LIST_PROJECT_DOCUMENT';
export const LIST_PROJECT_DOCUMENT_SUCCESS =
  'ACTION_LIST_PROJECT_DOCUMENT_SUCCESS';
export const LIST_PROJECT_DOCUMENT_OF_FOLDER =
  'ACTION_LIST_PROJECT_DOCUMENT_OF_FOLDER';
export const LIST_PROJECT_DOCUMENT_OF_FOLDER_SUCCESS =
  'ACTION_LIST_PROJECT_DOCUMENT_OF_FOLDER_SUCCESS';
export const LIST_DOCUMENT_FROM_ME = 'ACTION_LIST_DOCUMENT_FROM_ME';
export const LIST_DOCUMENT_FROM_ME_SUCCESS =
  'ACTION_LIST_DOCUMENT_FROM_ME_SUCCESS';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const LIST_DOCUMENT_SHARE = 'ACTION_LIST_DOCUMENT_SHARE';
export const LIST_DOCUMENT_SHARE_SUCCESS = 'ACTION_LIST_DOCUMENT_SHARE_SUCCESS';
export const TOGGLE_BUTTON_SIGNOUT_GOOGLE = 'TOGGLE_BUTTON_SIGNOUT_GOOGLE';
export const LIST_GOOGLE_DOCUMENT = 'LIST_GOOGLE_DOCUMENT';
export const LIST_GOOGLE_DOCUMENT_SUCCESS = 'LIST_GOOGLE_DOCUMENT_SUCCESS';