export const SCHEDULE_LIST = "ACTION_SCHEDULE_LIST";
export const SCHEDULE_LIST_FAIL = "ACTION_SCHEDULE_LIST_FAIL";
export const SCHEDULE_LIST_SUCCESS = "ACTION_SCHEDULE_LIST_SUCCESS";

export const SCHEDULE_OF_WEEK_LIST = "ACTION_SCHEDULE_OF_WEEK_LIST";
export const SCHEDULE_OF_WEEK_LIST_SUCCESS = "ACTION_SCHEDULE_OF_WEEK_LIST_SUCCESS";
export const SCHEDULE_OF_WEEK_LIST_FAIL = "ACTION_SCHEDULE_OF_WEEK_LIST_FAIL";


export const LIST_WEEKS_IN_YEAR = "ACTION_LIST_WEEKS_IN_YEAR";
export const LIST_WEEKS_IN_YEAR_SUCCESS = "ACTION_LIST_WEEKS_IN_YEAR_SUCCESS";
export const LIST_WEEKS_IN_YEAR_FAIL = "ACTION_LIST_WEEKS_IN_YEAR_FAIL";


export const SETTING_STARTING_DAY = "ACTION_SETTING_STARTING_DAY";
export const SETTING_STARTING_DAY_SUCCESS = "ACTION_SETTING_STARTING_DAY_SUCCESS";
export const SETTING_STARTING_DAY_FAIL = "ACTION_SETTING_STARTING_DAY_FAIL";

export const CREATE_SCHEDULE = "ACTION_CREATE_SCHEDULE";
export const CREATE_SCHEDULE_SUCCESS = "ACTION_CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAIL = "ACTION_CREATE_SCHEDULE_FAIL";

export const UPDATE_SCHEDULE = "ACTION_UPDATE_SCHEDULE";
export const UPDATE_SCHEDULE_SUCCESS = "ACTION_UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAIL = "ACTION_UPDATE_SCHEDULE_FAIL";


export const DELETE_SCHEDULE = "ACTION_DELETE_SCHEDULE";
export const DELETE_SCHEDULE_SUCCESS = "ACTION_DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAIL = "ACTION_DELETE_SCHEDULE_FAIL";